#
# ASMC benchmarking. This script is assumed to be running on 
# Stats department computer "rockpigeon", via an agent running
# inside a Singularity instance.
#

trigger: none

pr: none

schedules:
- cron: "30 * * * *"
  displayName: Hourly next benchmark
  branches:
    include:
    - master
  always: true

jobs:

- job: RunEverything
  
  displayName: Master job to run all steps
  
  variables:
    benchDir: /data/rockpigeon/cooper/ASMC-benchmark
    buildDir: $(benchDir)/__asmc_build

  pool:
    name: 'singularity'

  steps:

  - checkout: none # don't actually check out source - we work on an existing directory

  - script: |
      git fetch --all
      git reset --hard origin/master
    workingDirectory: $(benchDir)
    displayName: Ensure ASMC-benchmark is at origin/master

  - script: git submodule foreach git pull origin master
    workingDirectory: $(benchDir)
    displayName: Ensure ASMC submodule is at origin/master

  - script: mkdir -p $(buildDir)
    displayName: Create build directory

  - script: cmake ../ASMC -DCMAKE_BUILD_TYPE=Release
    workingDirectory: $(buildDir)
    displayName: CMake configure step

  - script: cmake --build . -j -- ASMC_exe
    workingDirectory: $(buildDir)
    displayName: CMake build step

  - script: python3 asmc-benchmark.py
    workingDirectory: $(benchDir)
    displayName: Run benchmark
    failOnStderr: true  # any printing to stderr results in a failure
    timeoutInMinutes: 45  # 0.75 hour failsafe on script

  - script: echo $(Build.ArtifactStagingDirectory)
    displayName: Where is the staging directory

  - task: CopyFiles@2
    inputs:
      sourceFolder: $(benchDir)
      contents: '*.svg'
      targetFolder: $(Build.ArtifactStagingDirectory)
      cleanTargetFolder: true
      overWrite: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: profiles

  - script: rm -rf $(buildDir)
    condition: always()
    displayName: Clean build directory
